# Generated by Django 3.2.9 on 2021-11-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortURL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLmanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lurl', models.CharField(max_length=256)),
                ('surl', models.CharField(max_length=16)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
